name: 'Barsali_Second_Custom'
description: 'Save the Report on Firebase'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Verifica File
      run: |
        ls
        cat ./JsonTestReport.json
        cat JsonTestReport.json
        #`cat JsonTestReport.json`
      shell: bash

    - name: Operazioni Firebase DB
      uses: w9jds/firebase-action@master
      with:
        args: database:set --force --debug  --project databasericette-beeb7 /giuseppegargani/ecchime JsonTestReport.json
      env:
        GCP_SA_KEY: ${{ secrets.FIREBASE_CREDENTIALS }}
